microsoftgraph/msgraph-beta-sdk-java

- build.gradle
> - replaces gradle upgrade fixes from core

- Scripts/getLatestVersion.ps1
- Scripts/validateMavenVersion.ps1
- adds missing scripts for automated creation of github release (copied from java core)
- fixes #8
> - fixes #8: adds missing scripts for github release

- README.md
related https://github.com/microsoftgraph/msgraph-sdk-java/pull/439
> - adds link to v1 and lints

- build.gradle
reflection of https://github.com/microsoftgraph/msgraph-sdk-java/pull/444
> - removes a task injection that was forgotten in previous updates

- README.md
> - documents additional repo to add for maven

- .azure-pipelines/generate-beta-models.yml
- src/main/java/com/microsoft/graph/requests/extensions/BaseGraphServiceClient.java
> - fixes default endpoint to beta

- Scripts/incrementMinorVersion.ps1
Linux runners require case sensitivity.
> Case sensitive README.md

- CODE_OF_CONDUCT.md
- SECURITY.md
- adds security policy
- adds code of conduct
> - adds security policy

- README.md
- build.gradle
- gradle.properties
- typesummary/app/build.gradle
partial https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/131
> - removes bintray in anticipation for service sunset

- .github/workflows/create-beta-pull-request.yml
- removes darrel from generation comment to save him notifications
> - removes darrel from generation comment to save him notifications

- README.md
- src/main/java/com/microsoft/graph/requests/GraphServiceClient.java
- fixes a generic type warning
> - fixes a bug where clients would get a warning because of a missing generic type

- android/build.gradle
- corrects rule name in disable section
> - replaces rule name to properly disable the false negative

- .github/workflows/create-beta-pull-request.yml
> - updates generation assignment to ramses

- android/build.gradle
> - updates the target android api level version

- .azure-pipelines/buildAndPackage.yml
- .azure-pipelines/templates/alert-failure.yml
- .azure-pipelines/templates/build-and-coverage.yml
- .azure-pipelines/templates/publish-artifacts.yml
- .azure-pipelines/templates/secure-files.yml
Fixes #
Folder .azure-pipelines has been added to include the .yml pipeline files.
Folder .azure-pipelines/templates/ has been added to organize pipeline tasks such that they mirror the organization model in the other Java SDK libraries.   
-
-
> Organized pipelines to be in line with the other Java SDK libraries

- .azure-pipelines/buildAndPackage.yml
- .azure-pipelines/templates/alert-failure.yml
- .azure-pipelines/templates/build/checkout-and-credscan.yml
- .azure-pipelines/templates/version-and-release.yml
- Fixed stage name
- Credscan to V2
- Alert Failure file removed
> fixed stage names, git connection, and credscan version

- .github/workflows/api-level-lint.yml
- .github/workflows/codeql-analysis.yml
https://github.com/microsoftgraph/msgraph-sdk-java/pull/879
> - adds worfkow dispatch trigger to codeQL and api level lint

- CHANGELOG.md
> edit change log

- .github/workflows/gradle-build.yml
- .github/workflows/preview-and-release.yml
> - replaces path by path ignore so CI triggers on dependabot PRs

- .github/workflows/create-beta-pull-request.yml
Dispatch Workflows for CI, Code QL, and api Level Lint from bot PR creation using Workflow Dispatch task.
> Dispatch Workflows from PR creation

- .github/workflows/gradle-build.yml
Steps for using Pkg Diff in the Build CI Workflow
fixes https://github.com/microsoftgraph/msgraph-sdk-java/issues/828
> Add Package DIff Step to CI Build

- .github/workflows/gradle-build.yml
Removing lines intended for testing
> Cleaning up build workflow

- .github/dependabot.yml
- android/build.gradle
> - updates target sdk version and adds dependabot configuration for android project

- android/gradle/wrapper/gradle-wrapper.properties
- gradle/wrapper/gradle-wrapper.properties
> - upgrades gradle wrapper to latest

- android/build.gradle
> Android Tools Update

- CHANGELOG.md
- gradle/dependencies.gradle
https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/483
> update core dependency to 2.0.12

- README.md
- gradle.properties
- src/main/java/com/microsoft/graph/info/Constants.java
forgot to change some values when bumping the core dependency
> Update values for 0.46.0

- android/build.gradle
> - bumps the android api level to latest to avoid build failures

- .github/workflows/preview-and-release.yml
https://github.com/microsoftgraph/msgraph-sdk-java/pull/1158
> Enable Feature/6.0 preview release

- .github/workflows/api-level-lint.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/gradle-build.yml
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
> - fixes triggers for preview version

- README.md
Readme update 
These steps will fail as preview has been blocked due to heap size. 
Once heap size is addressed (#383) we can release the preview and these steps will work.
> Update README.md for 6.0 preview. 

- android/build.gradle
> Update android Build.Gradle

- src/main/java/com/microsoft/serviceClient/GraphServiceClient.java
> Annotations for GraphServiceClient

- .github/workflows/gradle-build.yml
Compare Kiota Pkgs during pkgdiff step.
> Update Kiota PkgDiff

- .github/CODEOWNERS
> Cleanup codeowners

- .github/dependabot.yml
> - adds groups configuration

- README.md
- gradle.properties
- gradle/dependencies.gradle
- src/main/java/com/microsoft/graph/beta/info/Constants.java
Bumps to 6.0.1
Depends on https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/1412
> bump to version 6.0.1 to clear up possible dependency misalignment

- README.md
- gradle/dependencies.gradle
Fixes #1860
- Removal of dependency on Google Guava
> Issue-1860: Remove dependency on Google Guava

- .github/workflows/preview-and-release.yml
> - fixes version referenced in the workflow as it was deleted by author

- CHANGELOG.md
- gradle.properties
- gradle/dependencies.gradle
- src/main/java/com/microsoft/graph/beta/info/Constants.java
> - fixes a dependencies misalignment issue

- Scripts/incrementMinorVersion.ps1
> - fixes extraneous new lines being added when incrementing version

- .github/workflows/auto-merge-dependabot.yml
- .github/workflows/conflicting-pr-label.yml
- .github/workflows/gradle-build.yml
> - fixes workflow triggers

- .github/policies/msgraph-beta-sdk-java-branch-protection.yml
- .github/release-please.yml
- .github/workflows/api-level-lint.yml
- .github/workflows/auto-merge-dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/conflicting-pr-label.yml
- .github/workflows/git-release.yml
- .github/workflows/gradle-build.yml
- .github/workflows/preview-and-release.yml
@baywet we can now make `main` the default branch
part of https://github.com/microsoftgraph/msgraph-sdk-java/issues/1978
> Change default branch to `main`

- .github/workflows/gradle-build.yml
similar to https://github.com/microsoftgraph/msgraph-sdk-java/pull/2023
> Fetch latest release tag as branch name for comparison

- .github/workflows/api-level-lint.yml
- .github/workflows/gradle-build.yml
related https://www.sonatype.com/blog/maven-central-and-the-tragedy-of-the-commons
> ci: adds missing gradle dependencies caching to CI

- .github/dependabot.yml
> Prevent duplicate dependabot PRs

- .github/workflows/preview-and-release.yml
Fixes failures introduced by previous change: https://github.com/microsoftgraph/msgraph-beta-sdk-java/actions/runs/10372095985/job/28713983886
> Fix artifact Id in release package validation workflow

- .github/dependabot.yml
> ci: adds junit groups de reduce the number of pull requests

- gradle/dependencies.gradle
> fix: empty request body with logging interceptor

- build.gradle
- gradle/dependencies.gradle
Fixes #1030 
Removes Junit and Mockito dependencies because there are no unit tests for this SDK. This will also reduce the number of dependabot PRs
> Removed Junit and Mockito dependencies

- android/build.gradle
unblocks https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/1056
> Update Android gradle build tools

- .github/workflows/api-level-lint.yml
Migrate 1es hosted pool to use pool hosted in protected subscription
https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/27632
Note that the name of this pool is intentional and does not contain a typo
> Migrate use of hosted pool

- gradle/dependencies.gradle
> Bump Graph core dependency
